"""add_rework_config_history_production_target_supervisor

Revision ID: 4cd7f6409ef4
Revises: 
Create Date: 2026-02-20 12:46:58.047588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision = '4cd7f6409ef4'
down_revision = '0001_base_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_targets',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('target_quantity', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_targets_target_date'), 'production_targets', ['target_date'], unique=True)
    op.create_table('rework_configs',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('rework_detail', sa.String(length=200), nullable=False),
    sa.Column('copq_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rework_configs_is_active'), 'rework_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_rework_configs_rework_detail'), 'rework_configs', ['rework_detail'], unique=True)
    op.create_table('rework_history',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('work_order_id', UUID(as_uuid=True), nullable=False),
    sa.Column('scan_record_id', UUID(as_uuid=True), nullable=False),
    sa.Column('rework_config_id', UUID(as_uuid=True), nullable=True),
    sa.Column('rework_detail', sa.String(length=200), nullable=False),
    sa.Column('copq_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stage_id', UUID(as_uuid=True), nullable=True),
    sa.Column('stage_name', sa.String(length=100), nullable=True),
    sa.Column('operator_name', sa.String(length=100), nullable=True),
    sa.Column('applied_by', sa.String(length=100), nullable=False),
    sa.Column('rework_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rework_config_id'], ['rework_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_record_id'], ['scan_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['production_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rework_history_is_active'), 'rework_history', ['is_active'], unique=False)
    op.create_index(op.f('ix_rework_history_rework_date'), 'rework_history', ['rework_date'], unique=False)
    op.create_index(op.f('ix_rework_history_scan_record_id'), 'rework_history', ['scan_record_id'], unique=False)
    op.create_index(op.f('ix_rework_history_work_order_id'), 'rework_history', ['work_order_id'], unique=False)
    op.add_column('scan_records', sa.Column('supervisor_id', UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_scan_records_supervisor_id', 'scan_records', 'operators', ['supervisor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_scan_records_supervisor_id', 'scan_records', type_='foreignkey')
    op.drop_column('scan_records', 'supervisor_id')
    op.drop_index(op.f('ix_rework_history_work_order_id'), table_name='rework_history')
    op.drop_index(op.f('ix_rework_history_scan_record_id'), table_name='rework_history')
    op.drop_index(op.f('ix_rework_history_rework_date'), table_name='rework_history')
    op.drop_index(op.f('ix_rework_history_is_active'), table_name='rework_history')
    op.drop_table('rework_history')
    op.drop_index(op.f('ix_rework_configs_rework_detail'), table_name='rework_configs')
    op.drop_index(op.f('ix_rework_configs_is_active'), table_name='rework_configs')
    op.drop_table('rework_configs')
    op.drop_index(op.f('ix_production_targets_target_date'), table_name='production_targets')
    op.drop_table('production_targets')
    # ### end Alembic commands ###
